version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: twenty-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twenty
    ports:
      - "15432:5432"
    volumes:
      - twenty_postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: twenty-redis
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - twenty_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  twenty_postgres_data:
  twenty_redis_data:
